version: '3'

services:
  db-app-back-1:
    container_name: db-app-back-1
    hostname: db-app-back-1
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  app-back-1:
    container_name: app-back-1
    hostname: app-back-1
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app-back-1
    ports:
      - '3000:3000'
    depends_on:
      - db-app-back-1
volumes:
  db-data:
networks:
  default:
    external:
      name: backend
